/// Generated by AssetsRefGenerator on 2020/05/08
class Res {
  static const String blur = "assets/images/blur.webp";
  static const String gif_demo = "assets/images/gif_demo.gif";
  static const String group = "assets/images/group.png";
  static const String group_active = "assets/images/group_active.png";
  static const String hero_demo = "assets/images/hero_demo.jpeg";
  static const String home = "assets/images/home.png";
  static const String home_active = "assets/images/home_active.png";
  static const String image_placeholder = "assets/images/image_placeholder.png";
  static const String mall = "assets/images/mall.png";
  static const String mall_active = "assets/images/mall_active.png";
  static const String mine = "assets/images/mine.png";
  static const String mine_active = "assets/images/mine_active.png";
  static const String page1 = "assets/images/pager/page1.jpg";
  static const String page2 = "assets/images/pager/page2.jpg";
  static const String page3 = "assets/images/pager/page3.jpg";
  static const String page4 = "assets/images/pager/page4.jpg";
  static const String subject = "assets/images/subject.png";
  static const String subject_active = "assets/images/subject_active.png";
  static const String wish = "assets/images/wish.png";
}
